### ISSUE TITLE
Compiler "protocol Hologram.Compiler.CallGraphBuilder not implemented" error since bf5124c

### ISSUE THREAD

**Issue by gregjohnsonsaltaire** [bartblast/hologram#74]
From bf5124c onwards on bare minimum layout and page am getting:

** (EXIT from #PID<0.93.0>) an exception was raised:
    ** (Protocol.UndefinedError) protocol Hologram.Compiler.CallGraphBuilder not implemented for %Hologram.Compiler.IR.Block{expressions: [%Hologram.Compiler.IR.FunctionCall{args: [%Hologram.Compiler.IR.ModuleType{module: AnekolWwwHolo.Pages.Home}, %Hologram.Compiler.IR.AtomType{value: :custom_layout}, %Hologram.Compiler.IR.ListType{data: []}], function: :apply, module: Kernel}]} of type Hologram.Compiler.IR.Block (a struct)
        (hologram 0.1.0) lib/hologram/compiler/call_graph_builder.ex:1: Hologram.Compiler.CallGraphBuilder.impl_for!/1
        (hologram 0.1.0) lib/hologram/compiler/call_graph_builder.ex:2: Hologram.Compiler.CallGraphBuilder.build/4

**Comment by gregjohnsonsaltaire** [comment]
c1f5f7b is all good ...

**Comment by gregjohnsonsaltaire** [comment]
sorry, 3fcf833 is all good ...

**Comment by bartblast** [comment]
Call graph builder protocol implementation for Block IR structs was missing, fixed here: https://github.com/bartblast/hologram/commit/e9df9eef0a009a67012f2e4b539d98a692fb4cd1
